const chat=document.querySelector("#chat");
const TASKS_MORE="✨ И это далеко не всё, что можно поручить нейросетям!";
const BENEFIT_MORE="💡 И это только часть возможностей, которые могут облегчить вашу работу.";
const MENU_MORE="✨ И это только начало! Нейросети могут облегчить гораздо больше задач в работе психолога. Выберите интересующее вас направление и посмотрите примеры.";
let locked=false;
let generation=0;
function infoPlaque(text,kind){let p=document.createElement("div");p.className="info-plaque "+kind;p.textContent=text;return p}
function now(){return new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}
function scrollEnd(){requestAnimationFrame(()=>chat.scrollTo({top:chat.scrollHeight,behavior:"smooth"}))}
function bubble(text,kind="bot"){let el=document.createElement("article");el.className="bubble "+(kind==="user"?"user":"");let body=document.createElement("div");body.textContent=text;el.append(body);let time=document.createElement("div");time.className="time";time.textContent=now()+(kind==="user"?" ✓✓":"");el.append(time);chat.append(el);scrollEnd();return el}
function buttons(items){let wrap=document.createElement("div");wrap.className="actions";items.forEach((it,i)=>{let b=document.createElement("button");b.type="button";b.className="btn "+(it.color||["blue","pink","lilac","coral","mint","yellow","purple","blue","pink","green"][i%10]);b.textContent=it.label;b.addEventListener("click",()=>{if(locked)return;wrap.remove();it.run()});wrap.append(b)});chat.append(wrap);scrollEnd()}
function art(topic,i){let a=document.createElement("div");a.className="art a"+(i+1);a.setAttribute("role","img");a.setAttribute("aria-label","Декоративная иллюстрация к теме "+topic.title);let device=document.createElement("div");device.className="device";let d=document.createElement("span");d.textContent=topic.icons[0];device.append(d);a.append(device);topic.icons.slice(0,4).forEach((icon,j)=>{let x=document.createElement("span");x.className="tile t"+(j+1);x.textContent=icon;a.append(x)});let label=document.createElement("div");label.className="art-label";label.textContent="✦ идеи • нейросети • творчество ✦";a.append(label);return a}
function start(){generation++;locked=false;chat.replaceChildren();bubble("Привет! Я покажу, какие задачи психолог может облегчить с помощью нейросетей, чтобы оставалось больше времени на клиентов, развитие практики и собственную жизнь.");question();menu()}
function question(){let el=bubble("Что бы вы хотели облегчить в своей работе прямо сейчас?");el.classList.add("question")}
function menuPlaque(){let p=infoPlaque(MENU_MORE,"menu-more");p.setAttribute("role","note");chat.append(p);scrollEnd()}
function menu(){buttons(topics.map((t,i)=>({label:t.title,run:()=>openTopic(i)})));menuPlaque()}
function home(){generation++;locked=false;chat.replaceChildren();question();menu()}
function openTopic(i){let t=topics[i];generation++;chat.replaceChildren();let el=bubble("");el.firstChild.remove();el.insertBefore(art(t,i),el.firstChild);let h=document.createElement("div");h.className="topic-title";h.textContent=t.title;let sh=document.createElement("div");sh.className="problem-title";sh.textContent="Знакомая ситуация?";let txt=document.createElement("div");txt.textContent=t.problem;el.insertBefore(h,el.lastChild);el.insertBefore(sh,el.lastChild);el.insertBefore(txt,el.lastChild);scrollEnd();let completed={tasks:false,benefit:false};function options(){let a=[];if(!completed.tasks)a.push({label:"Что можно поручить нейросети?",color:"blue",run:()=>{completed.tasks=true;showTasks(i);options()}});if(!completed.benefit)a.push({label:"В чём моя выгода?",color:"pink",run:()=>{completed.benefit=true;showBenefit(i);options()}});if(completed.tasks&&completed.benefit)nav();else buttons(a)}options()}
function showTasks(i){let el=bubble("");el.firstChild.remove();let h=document.createElement("strong");h.textContent="Нейросеть может:";el.insertBefore(h,el.lastChild);let ul=document.createElement("ul");ul.className="bullets";topics[i].tasks.forEach(t=>{let li=document.createElement("li");li.textContent=t;ul.append(li)});el.insertBefore(ul,el.lastChild);el.insertBefore(infoPlaque(TASKS_MORE,"tasks-more"),el.lastChild);scrollEnd()}
function showBenefit(i){let text=topics[i].benefit;let el=bubble("");el.firstChild.remove();let h=document.createElement("div");h.className="benefit-heading";h.textContent="✨ В чём моя выгода?";el.insertBefore(h,el.lastChild);let parts=text.split(/\n\n/).filter(Boolean);let icons=["⏳","💰","🌿","✨"];parts.forEach((part,j)=>{let row=document.createElement("div");row.className="benefit-row";let badge=document.createElement("span");badge.className="benefit-icon";badge.textContent=icons[j%icons.length];let body=document.createElement("span");body.textContent=part;row.append(badge,body);el.insertBefore(row,el.lastChild)});el.insertBefore(infoPlaque(BENEFIT_MORE,"benefit-more"),el.lastChild);scrollEnd()}
function nav(){buttons([{label:"🔙 Вернуться ко всем возможностям",run:home},{label:"💬 Задать вопрос Марии",color:"pink",run:contact},{label:"📲 Перейти в канал Марии",color:"mint",run:channel}])}
function choice(message,telegram,max){chat.replaceChildren();bubble(message);let wrap=document.createElement("div");wrap.className="actions";[{label:"Telegram",url:telegram,color:"blue"},{label:"MAX",url:max,color:"mint"}].forEach(it=>{let link=document.createElement("a");link.className="btn "+it.color;link.textContent=it.label;link.href=it.url;link.target="_blank";link.rel="noopener noreferrer";link.style.display="grid";link.style.placeItems="center";link.style.textDecoration="none";wrap.append(link)});let back=document.createElement("button");back.type="button";back.className="btn lilac";back.textContent="🔙 Вернуться ко всем возможностям";back.addEventListener("click",home);wrap.append(back);chat.append(wrap);scrollEnd()}
function contact(){choice("Где вам удобнее задать мне вопрос?","https://t.me/maria_vadimovna_psy","https://6max.ru/mariakoreneva")}
function channel(){choice("Где вам удобнее читать мой канал?","https://t.me/mariakoreneva_ai_psy","https://max.ru/channel_mariakoreneva_ai_psy")}
start();
